Libraries
```{r}
library(sandwich)
library(haven)
library(stargazer)
library(estimatr)
library(lmtest)
library(tidyverse)
library(wooldridge)
library(dplyr)
```

Data Importation
```{r}
#import dataset
data <- read.csv('allcontracts.csv')

#make values that will be in regressions numerically interpretted by R
as.numeric(data$Total.Contract.Value)
as.numeric(data$Team.Cap)
#remove any blank variables
data <- na.omit(data)
```

Baseline Regression
```{r}
#run a baseline regression with only variables of interest, logging all salary related variables
ols1 <- lm( log(Total.Contract.Value) ~ log(Team.Cap) + CBA.Binary, data= data)
```

Control Regression
```{r}

#add controls into baseline regressions
ols2 <- lm( log(Total.Contract.Value) ~ log(Team.Cap)  + (CBA.Binary)*factor(Round.Drafted) + factor(Position) + factor(Year.Drafted) + factor(Division) + Age , data= data)
#test for heteroskedasticty
bptest(ols2)

#use robust standard errors to attemply to control for heteroskedasticity
ols_se<- coeftest(ols2, vcov = vcovHC(ols2, type="HC0"))


```

FGLS
```{r}
#1. Run regression of y on x_1 ... X_k, get the residuals
ols3 <- lm( log(Total.Contract.Value) ~ log(Team.Cap)  + (CBA.Binary)*factor(Round.Drafted) + factor(Position) + factor(Year.Drafted) + factor(Division) + Age + factor(Team), data= data)
#test for heteroskedasticity
bptest(ols3)

#2. Create(log(u^2))
# We must square the residuals because they will equal zero otherwise -> OLS is doing its job. Then you log the results. Logging helps keep the numbers in a reasonable range (and ensures they aren't gigantic)
ols_resid = ols3$residuals
log_resid <- log(ols_resid^2)


#3 Run the regression using our residuals from step 2 on our x_1... x_k and get the fitted residuals from that regression (again)
resid_fit <-lm(log_resid ~ log(Team.Cap)  + (CBA.Binary)*factor(Round.Drafted) + factor(Position) + factor(Year.Drafted) + factor(Division) + Age , data= data)

hhat_log <- resid_fit$residuals

#4 Exponentiate the fitted values (recall the log step)
hhat <- exp(hhat_log)

W <-1/hhat

#5 Estimate using WLS 1/h_hat
fgls <- lm(log1p(Total.Contract.Value) ~ log(Team.Cap)  + (CBA.Binary)*factor(Round.Drafted) + factor(Position) + factor(Year.Drafted) + factor(Division) + Age, data=data, weights=W)

```

Output Table
```{r}
#input three regressions into stargazer
#remove general model names and numbers and rename with desired labels
#assign row labels for all rows that are being shown in regression
#omit certain variables that are in the regression but we do not want shown in our model
#add  lines below regression indicated which models the omitted variables were in
#remove dependent variable labels
#add source note
stargazer(ols1, ols2, fgls, type = "html", out = "590 Output.html", 
model.names = FALSE, model.numbers = FALSE,
column.labels = c("OLS", "Controls with SE", "FGLS"),
          covariate.labels = c("log of Team Salary Cap", "Presence of 2011 CBA","Drafted Round 2", "Drafted Round 3", "Drafted Round 4", "Drafted Round 5", "Drafted Round 6", "Drafted Round 7", "Post-2011 Round 2", "Post-2011 Round 3", "Post-2011 Round 4", "Post-2011 Round 5", "Post-2011 Round 6", "Post-2011 Round 7", "Constant"),
          omit= c("Position", "Year.Drafted", "Division", "Age"),
          add.lines = list(c("Position FE", "No", "Yes", "Yes", "Yes"), c("Year Drafted", "No", "Yes", "Yes", "Yes"), c("Division", "No", "Yes", "Yes", "Yes"), c("Age", "No", "Yes", "Yes", "Yes")),
          dep.var.labels.include = FALSE, 
          dep.var.caption = " ",
          flip = TRUE,
          notes = "Source: Spotrac.com")
```

Summary Statistics Table
```{r}
#create a summary statistics table with listed variables
#within the table produce the statistics minimum, mean, maximum, n and standard deviation
stargazer(data, type = "html", out = "590 Summary Stats.html",
          digits.extra = 2,
          column.sep.width = "10",
          covariate.labels = c("Round Drafted", "Pick Number", "Year Drafted", "CBA", "Team Salary Cap", "Age", "College Division", "Total Contract Value"),
          omit= c("Signing.Bonus", "Rookie.Year.Cap"),
          summary.stat = c("max", "mean", "min", "n", "sd"))
```

works referenced
- https://rpubs.com/marvinlemos/log-transformation (logs)
- https://www.geeksforgeeks.org/how-to-convert-character-to-numeric-in-r/ (numeric conversion)